version: "3.8"
services:
    tremulo_python_core:
        image: "python"
        container_name: "tremulo_python_core"
        networks:
            - backend
        restart: always

    tremulo_postgre_db:
        image: "postgres"
        container_name: "tremulo_postgre_db"
        volumes:
            - ./db-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - backend
        restart: always
        environment:
            POSTGRES_PASSWORD: test

    tremulo_postgre_adminer:
        image: adminer
        container_name: "tremulo_postgre_adminer"
        restart: always
        ports:
            - 8081:8081

networks:
    backend:
        name: backend_network